export const AJAX_BEGIN = 'AJAX_BEGIN'
export const AJAX_ERROR = 'AJAX_ERROR'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REDIRECTED = 'REDIRECTED'

export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS'
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS'
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS'
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS'

export const CREATE_FURNITURE_SUCCESS = 'CREATE_FURNITURE_SUCCESS'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
export const GOT_REVIEWS_SUCCESS = 'GOT_REVIEWS_SUCCESS'
