version: '3.6'

services: 
  smart-brain-api: 
    container_name: backend
#    image: node:carbon
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://root:1234@postgres:5432/smart-brain
      JWT_SECRET: JWT_SECRET
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    