export const AJAX_BEGIN = 'AJAX_BEGIN'
export const AJAX_ERROR = 'AJAX_ERROR'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const REDIRECTED = 'REDIRECTED'

export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS'
export const MESSAGE_ERROR = 'MESSAGE_ERROR'
export const MESSAGE_RESET = 'MESSAGE_RESET'

export const RECEIVED_YEARLY_DATA = 'RECEIVED_YEARLY_DATA'

export const RECEIVED_MONTHLY_DATA = 'RECEIVED_MONTHLY_DATA'
export const UPDATE_MONTH_SUCCESS = 'UPDATE_MONTH_SUCCESS'

export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS'
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS'
